services:
  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - 15672:15672
    env_file:
      - .env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  redis:
    container_name: redis
    image: redis:7-alpine
    hostname: redis
    command:
      redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  factory0:
    container_name: factory0
    hostname: factory0
    env_file:
      - .env
    ports:
      - ${SFTP_PORT}:${SFTP_PORT}
    environment:
      - SFTP_HOST=factory0
    build:
      context: .
      dockerfile: ./factory/Dockerfile
    volumes:
      - factory0:/factory/files/
    command:
      python3 -m src.main
    depends_on:
      - rabbitmq

  factory0_worker:
    container_name: factory0_worker
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./factory/Dockerfile
    volumes:
      - factory0:/factory/files/
    command:
      celery -A src.app:app worker -l INFO
    depends_on:
      - rabbitmq

  factory0_beat:
    container_name: factory0_beat
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./factory/Dockerfile
    volumes:
      - factory0:/factory/files/
    command:
      celery -A src.app:app beat -l INFO
    depends_on:
      - rabbitmq

  keeper_worker:
    image: keeper_worker
    container_name: keeper_worker
    env_file:
      - .env
    environment:
      - FACTORY_HOSTS=factory0,
    build:
      context: .
      dockerfile: ./keeper/Dockerfile
    command:
      celery -A src.app:app worker -l INFO
    depends_on:
      - factory0
      - rabbitmq
      - minio

  keeper_beat:
    image: keeper_beat
    container_name: keeper_beat
    env_file:
      - .env
    environment:
      - FACTORY_HOSTS=factory0,
    build:
      context: .
      dockerfile: ./keeper/Dockerfile
    command:
      celery -A src.app:app beat -l INFO
    depends_on:
      - factory0
      - rabbitmq

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - 9000:9000
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command:
      server /data

volumes:
  factory0:
  minio:
