services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"

  file_factory_worker:
    image: file_factory_worker
    container_name: file_factory_worker
    build:
      context: .
      dockerfile: ./file_factory/Dockerfile
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - SERVER=file_factory_worker
    volumes:
      - file_factory:/file_factory/files/
    command:
      celery -A src.app:app worker -l info
    depends_on:
      - rabbitmq
      - redis

  file_factory_beat:
    image: file_factory_beat
    container_name: file_factory_beat
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - SERVER=file_factory_worker
    build:
      context: .
      dockerfile: ./file_factory/Dockerfile
    volumes:
      - file_factory:/file_factory/files/
    command:
      celery -A src.app:app beat -l INFO
    depends_on:
      - rabbitmq
      - redis

  file_factory:
    image: file_factory
    container_name: file_factory
    hostname: file_factory
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - SERVER=server
    build:
      context: .
      dockerfile: ./file_factory/Dockerfile
    volumes:
      - file_factory:/file_factory/files/
    command:
      python3 src/main.py
    depends_on:
      - rabbitmq
      - redis
    ports:
      - 2222:2222

  file_keeper_worker:
    image: file_keeper_worker
    container_name: file_keeper_worker
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    build:
      context: .
      dockerfile: ./file_keeper/Dockerfile
    command:
      celery -A src.app:app worker -l info
    depends_on:
      - file_factory
      - rabbitmq
      - redis

  file_keeper_beat:
    image: file_keeper_beat
    container_name: file_keeper_beat
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    build:
      context: .
      dockerfile: ./file_keeper/Dockerfile
    command:
      celery -A src.app:app beat -l info
    depends_on:
      - file_factory
      - rabbitmq
      - redis


volumes:
  file_factory:
